baseURL = "https://buzati.com"
languageCode = "en-us"
title = "buzati"
theme = "digital-garden"
themesdir = "./themes/"
copyright = "buzati ©"


[params]
  name = "buzati"
#  description = ""
#  keywords = "notion, teamwork, projectmanagement"
  initials = "B"
  googleAnalytics = "G-EM91CJQ626"

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/buzatiHQ"
    icon = "fab fa-twitter"

#  [[params.social]]
#    name = "Github"
#    link = "#"
#    icon = "fab fa-github"

#  [[params.social]]
#    name = "Medium"
#    link = "#"
#    icon = "fab fa-medium-m"

#  [[params.social]]
#    name = "LinkedIn"
#    link = "#"
#    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5